### ISSUE TITLE
Code formatting 

### ISSUE THREAD

**Issue by mturalenka** [laterpay/laterpay-typo3-extension#68]
currently a lot of places where code is not aligned well, spaces amount  are wrong etc
additional task:
- update phpcs rules to check these issues

**Comment by yastapenko-ScnSoft** [comment]
@mturalenka the reason is that at many places code alined by tabs - there are about seven hundreds of strings with such alignment. The only way i see to add rule into php cs - is creation of sniff which disallow to use tab after some symbol in code. Even if this rule will be added - someone need to fix all this strings, and seems like it's about me, am i right?

**Comment by mturalenka** [comment]
@yastapenko-ScnSoft yep, ticket was assigned on you for that reason :smiley:
